name: GitHub Repo Mirroring

on:
  push:
    branches:
      - main  # Trigger on push to main branch (adjust as per your need)

jobs:
  mirror-repos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run mirror script
      env:
        GH_MIRROR_TOKEN: ${{ secrets.GH_MIRROR_TOKEN }}  # Use the secret here
      run: |
        python mirror.py
